[package]
name = "click-battler"
version = "0.1.0"
authors = ["David LeGare <dlegare.1001@gmail.com>"]
edition = "2018"

[dependencies]
warp = "0.1.19"
futures = "0.1.28"
pretty_env_logger = "0.3"
serde_derive = "1.0"
handlebars = "1.0.0"
